### ISSUE TITLE
Liste von Überweisungsempfänger alphabetisch sortieren

### ISSUE THREAD

**Issue by sicheste** [cod3monk/fsikasse#2]
Aktuell ist die Liste bei Überweisungsempfängern wohl auch nach deren Guthaben sortiert. Eine alphabetische Sortierung wäre hier sinnvoll.

**Comment by vivaeltopo** [comment]
Fixed! https://github.com/cod3monk/fsikasse/commit/ec5627eb1b01f8a2dd290acd017e59b421781211
