### ISSUE TITLE
Eingabe von Beträgen größer als 99 Cent fehlerhaft

### ISSUE THREAD

**Issue by sicheste** [cod3monk/fsikasse#4]
Werden Beträge größer als 99 Cent eingegeben (z.B. 5,00 €) so wird beim Übertrag der Ziffer auf die Position vor dem Komma nicht die richtige Ziffer übertragen. Dieser Fehler tritt aber nur am Bedienfeld auf, liegt somit wohl am Browser auf dem Raspberry.

**Comment by vivaeltopo** [comment]
Funktioniert unter nicht-ARM Systemen scheinbar problemlos. Evtl mal einen anderen Browser testen…
